name: go-short test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - name: Run tests
        uses: actions/setup-go@v2
        env:
          REDIS_HOST: redis://localhost:6379

      - name: Run tests
        run: go test -v ./...
